#!/bin/bash

# Prints out the bluetooth status

BLUETOOTH_ON_ICON='\uf2b4'
BLUETOOTH_OFF_ICON='\uf2b4'

get_bluetooth()
{
    status=$(systemctl is-active bluetooth.service)

    if [ "$status" == "active" ]
    then
        echo "$BLUETOOTH_ON_ICON"
    else
        :
        #echo "$BLUETOOTH_OFF_ICON"
    fi
}

get_bluetooth
