#!/bin/bash

# What modules, in what order
MODULES="hostname $(echo -e '\uf323 \uf323 \uf323 \uf323 \uf323 \uf323 \uf323') localip netdowntraffic netuptraffic disksize ram cpuload wifi bluetooth backlight volume battery time"

# Modules that require an active internet connection
ONLINE_MODULES="weather internet"

# Delay between showing the status bar
DELAY="0.05"

# Where the custom modules are stored
CUSTOM_DIR="/home/$USER/.config/dwmbar/modules/custom/"

# Separator between modules
SEPARATOR=" | "

# Padding at the end and beginning of the status bar
RIGHT_PADDING=" "
LEFT_PADDING=" "
